import { MainLayout } from './components'
import { primaryFont } from './fonts'
import './styles/globalStyles.scss'
import { DataProvider } from './context/DataProvider'

export const metadata = {
  title: 'Comesty store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={primaryFont.className}>
      <body>
        <MainLayout>
          <DataProvider>
            {children}
          </DataProvider>
        </MainLayout>
      </body>
    </html>
  )
}
