import { MainLayout } from './components'
import { primaryFont } from './fonts'
import './styles/globalStyles.scss'


export const metadata = {
  title: 'Comesty store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={primaryFont.className}>
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  )
}
